 - name: creating user roboshop
   ansible.builtin.user:
      name: roboshop

 - name: Recursively remove app directory
   ansible.builtin.file:
       path: /app
       state: absent

 - name: Create a directory 
   ansible.builtin.file:
       path: /app
       state: directory

 - name: Download catalogue application
   ansible.builtin.get_url:
       url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
       dest: /tmp

 - name: Extract file
   ansible.builtin.unarchive:
     src:  /tmp/catalogue.zip
     dest: /app
     remote_src: yes

  