
 - name: Copy catalogue service
   ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

 - name: deamon realod and start
   ansible.builtin.systemd_service:
    daemon_reload: true
  # let's start after the data is loaded
  
 - name: start and enable catalogue
   ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes